name: nursery_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_calendar: ^28.2.5
  syncfusion_flutter_charts: ^28.2.5
  syncfusion_flutter_gauges: ^28.2.5
  syncfusion_flutter_datepicker: ^28.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
